In [62]:
#import the required libraries
import numpy as np
import pandas as pd

In [63]:
#reading the data
data = pd.read_csv("IndianLiverPatientData.txt", index_col=0,header=None,encoding = 'utf-8', sep = '\t', low_memory=False)
data.shape

(583, 11)

In [64]:
data.head(5)

1       2     3    4    5   6    7    8    9     10  11
0                                                         
1  65  Female   0.7  0.1  187  16   18  6.8  3.3  0.90  No
2  62    Male  10.9  5.5  699  64  100  7.5  3.2  0.74  No
3  62    Male   7.3  4.1  490  60   68  7.0  3.3  0.89  No
4  58    Male   1.0  0.4  182  14   20  6.8  3.4  1.00  No
5  72    Male   3.9  2.0  195  27   59  7.3  2.4  0.40  No

In [65]:
#naming the columns
data.columns=["Age","Gender","Total_Bilirubin","Direct_Bilirubin","Alkaline_Phosphotase",
"Alamine_Aminotransferase","Aspartate_Aminotransferase","Total_Protiens","Albumin",
"Albumin_and_Globulin_Ratio","Class"]


In [66]:
data.head(5)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0                                                                         
1   65  Female              0.7               0.1                   187   
2   62    Male             10.9               5.5                   699   
3   62    Male              7.3               4.1                   490   
4   58    Male              1.0               0.4                   182   
5   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                                                                         
1                        16                          18             6.8   
2                        64                         100             7.5   
3                        60                          68             7.0   
4                        14                          20             6.8   
5                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio Class  
0                                             
1      3.3                        0.90    No  
2      3.2                        0.74    No  
3      3.3                        0.89    No  
4      3.4                        1.00    No  
5      2.4                        0.40    No

In [67]:
#checking the null values
data.isnull().sum()

Age                            0
Gender                        20
Total_Bilirubin                0
Direct_Bilirubin               0
Alkaline_Phosphotase           0
Alamine_Aminotransferase       0
Aspartate_Aminotransferase     0
Total_Protiens                15
Albumin                        0
Albumin_and_Globulin_Ratio     4
Class                          0
dtype: int64

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 583 entries, 1 to 583
Data columns (total 11 columns):
Age                           583 non-null int64
Gender                        563 non-null object
Total_Bilirubin               583 non-null float64
Direct_Bilirubin              583 non-null float64
Alkaline_Phosphotase          583 non-null int64
Alamine_Aminotransferase      583 non-null int64
Aspartate_Aminotransferase    583 non-null int64
Total_Protiens                568 non-null float64
Albumin                       583 non-null float64
Albumin_and_Globulin_Ratio    579 non-null float64
Class                         583 non-null object
dtypes: float64(5), int64(4), object(2)
memory usage: 54.7+ KB


In [69]:
#replace the missing values with mode values
data['Gender'].fillna(data['Gender'].mode()[0],inplace=True)

In [70]:
data.isnull().sum()

Age                            0
Gender                         0
Total_Bilirubin                0
Direct_Bilirubin               0
Alkaline_Phosphotase           0
Alamine_Aminotransferase       0
Aspartate_Aminotransferase     0
Total_Protiens                15
Albumin                        0
Albumin_and_Globulin_Ratio     4
Class                          0
dtype: int64

In [71]:
data['Gender'].mode()[0]

'Male'

In [72]:
#replace the missing values with mean values
for value in ['Total_Protiens','Albumin_and_Globulin_Ratio']:
    data[value].fillna(data[value].mean(),inplace=True)

In [73]:
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Class                         0
dtype: int64

In [74]:
data.head(5)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0                                                                         
1   65  Female              0.7               0.1                   187   
2   62    Male             10.9               5.5                   699   
3   62    Male              7.3               4.1                   490   
4   58    Male              1.0               0.4                   182   
5   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                                                                         
1                        16                          18             6.8   
2                        64                         100             7.5   
3                        60                          68             7.0   
4                        14                          20             6.8   
5                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio Class  
0                                             
1      3.3                        0.90    No  
2      3.2                        0.74    No  
3      3.3                        0.89    No  
4      3.4                        1.00    No  
5      2.4                        0.40    No

In [75]:
#fetching the categorical variable
colname=[]
for x in data.columns:
    if data[x].dtype=='object':
        colname.append(x)
colname

['Gender', 'Class']

In [76]:
# For preprocessing the data
#Converting the categorical variable to numeric 
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    data[x]=le.fit_transform(data[x])

In [79]:
data.head(5)
#0-----NO
#1-----YES

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0                                                                         
1   65       0              0.7               0.1                   187   
2   62       1             10.9               5.5                   699   
3   62       1              7.3               4.1                   490   
4   58       1              1.0               0.4                   182   
5   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                                                                         
1                        16                          18             6.8   
2                        64                         100             7.5   
3                        60                          68             7.0   
4                        14                          20             6.8   
5                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Class  
0                                              
1      3.3                        0.90      0  
2      3.2                        0.74      0  
3      3.3                        0.89      0  
4      3.4                        1.00      0  
5      2.4                        0.40      0

In [80]:
data.Class.value_counts()

0    416
1    167
Name: Class, dtype: int64

In [81]:
#CREATING X AND Y
X=data.values[:,0:-1]
Y=data.values[:,-1]

In [82]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
print(X)

[[ 1.25209764 -1.76228085 -0.41887783 ...  0.29560659  0.19896867
  -0.14789798]
 [ 1.06663704  0.56744644  1.22517135 ...  0.95038755  0.07315659
  -0.65069686]
 [ 1.06663704  0.56744644  0.6449187  ...  0.48268687  0.19896867
  -0.17932291]
 ...
 [ 0.44843504  0.56744644 -0.4027597  ... -0.07855395  0.07315659
   0.16635131]
 [-0.84978917  0.56744644 -0.32216906 ...  0.29560659  0.32478075
   0.16635131]
 [-0.41704777  0.56744644 -0.37052344 ...  0.76330728  1.58290153
   1.73759779]]


In [83]:
#SPLITING THE DATA INTO TRAIN AND TEST
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state=10)

In [84]:
#BUILDING THE MODEL
from sklearn.linear_model import LogisticRegression

#create a model
classifier=LogisticRegression()

#build train the model
classifier.fit(X_train,Y_train)

#predict using the model you created
Y_pred=classifier.predict(X_test)

#we areusing this for comparision
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[-0.41100149 -0.00634302 -0.33998569 -0.8632961  -0.37864429 -1.28333153
  -0.82794328 -0.5558285   0.66883943 -0.19326795]]
[-1.72162906]


In [85]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm = confusion_matrix(Y_test,Y_pred)
print(cfm)

print("CLASSIFICATION MATRIX:")
print(classification_report(Y_test,Y_pred))

acc = accuracy_score(Y_test,Y_pred)
print("ACCURACY OF THE MODEL:",acc)

[[114  12]
 [ 40   9]]
CLASSIFICATION MATRIX:
              precision    recall  f1-score   support

         0.0       0.74      0.90      0.81       126
         1.0       0.43      0.18      0.26        49

    accuracy                           0.70       175
   macro avg       0.58      0.54      0.54       175
weighted avg       0.65      0.70      0.66       175

ACCURACY OF THE MODEL: 0.7028571428571428


In [86]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [87]:
# from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[108  18]
 [ 33  16]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.77      0.86      0.81       126
         1.0       0.47      0.33      0.39        49

    accuracy                           0.71       175
   macro avg       0.62      0.59      0.60       175
weighted avg       0.68      0.71      0.69       175

Accuracy of the model:  0.7085714285714285


In [88]:
#we are performing over sampling
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = data[data.Class==0]
df_minority = data[data.Class==1]

# Upsample minority class
df_minority_upsampled = resample(df_minority,
replace=True, # sample with replacement
n_samples=416, # to match majority class
random_state=10) # reproducible results

# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

# Display new class counts
df_upsampled.Class.value_counts()

1    416
0    416
Name: Class, dtype: int64

In [89]:
data.Class.value_counts()

0    416
1    167
Name: Class, dtype: int64

In [90]:
X = df_upsampled.values[:,:-1]
Y = df_upsampled.values[:,-1]

In [91]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
print(X)

[[ 1.31929811 -1.73762012 -0.36813594 ...  0.25968092  0.12505717
  -0.20458913]
 [ 1.13104244  0.57549978  1.55193588 ...  0.91099575  0.00192396
  -0.71425759]
 [ 1.13104244  0.57549978  0.87426347 ...  0.44577088  0.12505717
  -0.2364434 ]
 ...
 [-0.18674721 -1.73762012 -0.33048747 ...  1.00404073  0.74072321
   0.11395366]
 [-0.87701797 -1.73762012 -0.34931171 ...  1.28317566  1.60265568
   1.06958203]
 [-0.56325853  0.57549978 -0.33048747 ... -0.11249898  0.4944568
   0.75103924]]


In [92]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state=10)

In [93]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [94]:
# from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 94  36]
 [  7 113]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.93      0.72      0.81       130
         1.0       0.76      0.94      0.84       120

    accuracy                           0.83       250
   macro avg       0.84      0.83      0.83       250
weighted avg       0.85      0.83      0.83       250

Accuracy of the model:  0.828
